version: '3.7'

services:
    mongo: 
      image: mongo
      restart: always
      volumes: 
        - ./data:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - 27017:27017